### ISSUE TITLE
Define inputImagePath and outputImagePath

### ISSUE THREAD

**Issue by Alexandre-Muzulao** [Remove-Background-ai/rembg.js#4]
Hello,  I hope to find you well!

I have a problem to use rembg, without a parameter outputImagePath, becouse, when the method execut, and do the output file, the resoult outputImagePath is ever:  C:\\undefined\temp\rembg--5232-797vlvU7lrHi-.png and I need set an defined file path for my context.

Do you can help me please?

**Comment by mtrabelsi** [comment]
Hi, the issue is inherited from **tmp-promise** it looks like it is not working very well under Windows, I will check that issue later or look for an alternative solution.


but for now, you can still use base64 to overcome this issue,  this feature has been added to 1.1.2, please upgrade your current version. 

https://www.npmjs.com/package/@remove-background-ai/rembg.js/v/1.1.2
